KBUILD_CFLAGS += -Werror
obj-y += rtk_gpio.o
obj-y += rtk_gpio-dev.o
obj-y += rtk_gpio-db.o
obj-y += rtk_gpio-debug.o
obj-$(CONFIG_RTK_KDRV_GPIO_BUILT_IN_TEST) += rtk_gpio-bist.o
obj-$(CONFIG_RTK_KDRV_GPIO_WITH_SYSFS_DEBUG) += rtk_gpio-attr.o
obj-$(CONFIG_RTK_KDRV_GPIO_GPIOLIB_SUPPORT) += rtk_gpio-chipset.o
