# Makefile for the Realtek scaler control drivers.
#
obj-y := scalerstruct.o scalercolorlib.o scalerthread_rtice2ap.o scalercolorlib_tv001.o scalercolorlib_IPQ.o scalercolorlib_tv010.o scalercolorlib_tv002.o scalercolor_engmenu.o scalercolorlib_AIPQ.o
#scalerLib.o scalerAdc.o scalerVideo.o scalerAtv.o scalerMsgDispatch.o scalerAPI.o scalerVBI.o scalerVerify.o scalerEyeGuard.o scalerColorLib.o

KBUILD_CFLAGS +=  -Werror

