# Makefile for the Realtek Audio HW drivers.
#
obj-y := audio_hw_driver.o audio_hw_log.o audio_hw_ioctl.o audio_hw_aio.o audio_hw_app.o audio_hw_atv.o audio_hw_rpc.o audio_hw_pm.o audio_hw_factory.o audio_hw_earc_driver.o audio_hw_earc_ioctl.o audio_hw_earc_pm.o
KBUILD_CFLAGS += -Werror