#
# Makefile for the Realtek rsa drivers.
#

ifdef CONFIG_RTK_KDRV_MCP_RSA
obj-y += rtk_rsa_api.o rtk_rsa_lib.o rtk_rsa_util.o rtk_rsa_hw_fun.o
endif

ifdef CONFIG_RTK_KDRV_MCP_RSA_TEST
obj-y += rtk_rsa_test.o
endif
