#
# Makefile for the linux kernel.
#

#KBUILD_CFLAGS += -Wall -Werror

obj-$(CONFIG_RTK_KDRV_ATSC3_DMX) += alp_lib.o alp_mpeg2_ts.o
obj-$(CONFIG_RTK_KDRV_ATSC3_DMX)  += bbp_lib.o
obj-$(CONFIG_RTK_KDRV_ATSC3_DMX)  += oif_lib.o
obj-$(CONFIG_RTK_KDRV_ATSC3_DMX)  += ring.o
obj-$(CONFIG_RTK_KDRV_ATSC3_DMX)  += atsc3_dmx.o

