#Copyright (C) 2007-2014 Realtek Semiconductor Corporation.

KBUILD_CFLAGS += -Wall -Werror

obj-$(CONFIG_RTK_KDRV_TP) += $(TP_PATH)/

obj-y = tp_drv.o \
		tp_drv_verify.o \
		tp_drv_global.o \
        tp_drv_api.o \
        tp_reg_ctrl.o \
		tp_drv_lock.o \
		tp_drv_dump.o \
		tp_ta.o
