#ifndef _RTK_VIP_LOGGER_H
#define _RTK_VIP_LOGGER_H
#include <mach/rtk_log.h>

/*define log level*/
#define VIP_LOGLEVEL_ERR	KERN_EMERG
#define VIP_LOGLEVEL_WARNING	KERN_WARNING
#define VIP_LOGLEVEL_DEBUG	KERN_DEBUG
#define VIP_LOGLEVEL_INFO	KERN_INFO

/**
	Use 10bit integer to identify an interface who need ctrl its debug log.
	b'[9:8]: 0x0 for ctrl enable of all vip log. 0x1~0x3 means id of module.
	b'[7:3]: 0x0 for ctrl enable of all log belong to a module. 0x1~0x1f means id of ip belong to the module.
	b'[2:0]: 0x0 for ctrl enable of all log belgong to the ip or sub-module. 0x1~0x7 means id of the interface belong to the ip.
**/
#define VIP_LOGMODULE_DEFINE(x) 	(((x) & 0x3) << 8)
#define VIP_LOGIP_DEFINE(x,y)		((x) | (((y) & 0x1f) << 3))
#define VIP_LOGINTERFACE_DEFINE(x,y)	((x) | ((y) & 0x7))
//Modules define
#define VIP_LOGMODULE_DEBUG		VIP_LOGMODULE_DEFINE(0x0)
#define VIP_LOGMODULE_MEMC_DEBUG	VIP_LOGMODULE_DEFINE(0x1)
#define VIP_LOGMODULE_VGIP_DEBUG	VIP_LOGMODULE_DEFINE(0x2)
#define VIP_LOGMODULE_VIP_DEBUG		VIP_LOGMODULE_DEFINE(0x3)
//Debug log interface belong to MEMC
#define VIP_LOGMODULE_MEMC_IP1_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_MEMC_DEBUG,0x1)
#define VIP_LOGMODULE_MEMC_IP1_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP1_DEBUG,0x1)
#define VIP_LOGMODULE_MEMC_IP1_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP1_DEBUG,0x7)

#define VIP_LOGMODULE_MEMC_IP31_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_MEMC_DEBUG,0x1F)
#define VIP_LOGMODULE_MEMC_IP31_interface1_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP31_DEBUG,0x1)
#define VIP_LOGMODULE_MEMC_IP31_interface2_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP31_DEBUG,0x2)
#define VIP_LOGMODULE_MEMC_IP31_interface3_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP31_DEBUG,0x3)
#define VIP_LOGMODULE_MEMC_IP31_interface4_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP31_DEBUG,0x4)
#define VIP_LOGMODULE_MEMC_IP31_interface5_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP31_DEBUG,0x5)
#define VIP_LOGMODULE_MEMC_IP31_interface6_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP31_DEBUG,0x6)
#define VIP_LOGMODULE_MEMC_IP31_interface7_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_MEMC_IP31_DEBUG,0x7)

//Debug log interface belong to VGIP
#define VIP_LOGMODULE_VGIP_DCC_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x1)//Ctrl enable of all interfaces belong to VGIP's DCC
#define VIP_LOGMODULE_VGIP_DCC_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DCC_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_DCC_interface2_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DCC_DEBUG,0x2)
#define VIP_LOGMODULE_VGIP_DCC_interface3_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DCC_DEBUG,0x3)
#define VIP_LOGMODULE_VGIP_DCC_interface4_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DCC_DEBUG,0x4)
#define VIP_LOGMODULE_VGIP_DCC_interface5_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DCC_DEBUG,0x5)
#define VIP_LOGMODULE_VGIP_DCC_interface6_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DCC_DEBUG,0x6)
#define VIP_LOGMODULE_VGIP_DCC_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DCC_DEBUG,0x7)

#define VIP_LOGMODULE_VGIP_DI_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x2)//Ctrl enable of all interfaces belong to VGIP's DI
#define VIP_LOGMODULE_VGIP_DI_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DI_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_DI_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_DI_DEBUG,0x7)

#define VIP_LOGMODULE_VGIP_Video_DEBUG		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x3)//Ctrl enable of all interfaces belong to VGIP's Video
#define VIP_LOGMODULE_VGIP_Video_GeneralStatus_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Video_DEBUG, 0x1)
#define VIP_LOGMODULE_VGIP_Video_SettingStatus_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Video_DEBUG, 0x2)
#define VIP_LOGMODULE_VGIP_Video_SpecialFlag_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Video_DEBUG, 0x3)
#define VIP_LOGMODULE_VGIP_Video_VectorBinRatio_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Video_DEBUG, 0x4)
#define VIP_LOGMODULE_VGIP_Video_DynamicControl_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Video_DEBUG, 0x5)
#define VIP_LOGMODULE_VGIP_Video_interface6_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Video_DEBUG, 0x6)
#define VIP_LOGMODULE_VGIP_Video_ErrorStatus_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Video_DEBUG, 0x7)

#define VIP_LOGMODULE_VGIP_VIP_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x4)//Ctrl enable of all interfaces belong to VGIP's VIP
#define VIP_LOGMODULE_VGIP_VIP_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_VIP_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_VIP_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_VIP_DEBUG,0x7)

#define VIP_LOGMODULE_VGIP_PQA_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x5)//Ctrl enable of all interfaces belong to VGIP's VIP
#define VIP_LOGMODULE_VGIP_PQA_Info1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_PQA_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_PQA_Info2_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_PQA_DEBUG,0x2)
#define VIP_LOGMODULE_VGIP_PQA_Info3_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_PQA_DEBUG,0x3)
#define VIP_LOGMODULE_VGIP_PQA_Info4_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_PQA_DEBUG,0x4)
#define VIP_LOGMODULE_VGIP_PQA_Info5_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_PQA_DEBUG,0x5)
#define VIP_LOGMODULE_VGIP_PQA_Info6_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_PQA_DEBUG,0x6)
#define VIP_LOGMODULE_VGIP_PQA_Info7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_PQA_DEBUG,0x7)

#define VIP_LOGMODULE_VGIP_CalInfo_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x6)//Ctrl enable of all interfaces belong to VGIP's VIP
#define VIP_LOGMODULE_VGIP_CalInfo_MadHist_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_CalInfo_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_CalInfo_PQASPM_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_CalInfo_DEBUG,0x2)
#define VIP_LOGMODULE_VGIP_CalInfo_FMCHMC_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_CalInfo_DEBUG,0x3)
#define VIP_LOGMODULE_VGIP_CalInfo_YHueSatHist_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_CalInfo_DEBUG,0x4)
#define VIP_LOGMODULE_VGIP_CalInfo_BitRate_Ctrl_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_CalInfo_DEBUG,0x5)
#define VIP_LOGMODULE_VGIP_CalInfo_interface6_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_CalInfo_DEBUG,0x6)
#define VIP_LOGMODULE_VGIP_CalInfo_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_CalInfo_DEBUG,0x7)

#define VIP_LOGMODULE_VGIP_ID_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x7)//Ctrl enable of all interfaces belong to VGIP's VIP
#define VIP_LOGMODULE_VGIP_ID_Number_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_ID_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_ID_YHist_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_ID_DEBUG,0x2)
#define VIP_LOGMODULE_VGIP_ID_Hue_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_ID_DEBUG,0x3)
#define VIP_LOGMODULE_VGIP_ID_Sat_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_ID_DEBUG,0x4)
#define VIP_LOGMODULE_VGIP_ID_Identiy_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_ID_DEBUG,0x5)
#define VIP_LOGMODULE_VGIP_ID_interface6_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_ID_DEBUG,0x6)
#define VIP_LOGMODULE_VGIP_ID_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_ID_DEBUG,0x7)

#define VIP_LOGMODULE_VGIP_Decontour_DEBUG		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x8)
#define VIP_LOGMODULE_VGIP_Decontour_1_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Decontour_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_Decontour_2_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Decontour_DEBUG,0x2)
#define VIP_LOGMODULE_VGIP_Decontour_3_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Decontour_DEBUG,0x3)
#define VIP_LOGMODULE_VGIP_Decontour_4_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Decontour_DEBUG,0x4)
#define VIP_LOGMODULE_VGIP_Decontour_5_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Decontour_DEBUG,0x5)
#define VIP_LOGMODULE_VGIP_Decontour_6_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Decontour_DEBUG,0x6)
#define VIP_LOGMODULE_VGIP_Decontour_7_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_Decontour_DEBUG,0x7)

#define VIP_LOGMODULE_VGIP_IP31_DEBUG		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VGIP_DEBUG,0x1f)
#define VIP_LOGMODULE_VGIP_IP31_interface1_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_IP31_DEBUG,0x1)
#define VIP_LOGMODULE_VGIP_IP31_interface7_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VGIP_IP31_DEBUG,0x7)

//Debug log interface belong to VIP
#define VIP_LOGMODULE_VIP_RGBW_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x1)//Ctrl enable of all interfaces belong to VIP's RGBW
#define VIP_LOGMODULE_VIP_RGBW_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_RGBW_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_RGBW_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_RGBW_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_COLOR_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x2)//Ctrl enable of all interfaces belong to VIP's Color
#define VIP_LOGMODULE_VIP_COLOR_color_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_COLOR_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_COLOR_scaler_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_COLOR_DEBUG,0x2)

#define VIP_LOGMODULE_VIP_DCC_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x3)//Ctrl enable of all interfaces belong to VIP's DCC
#define VIP_LOGMODULE_VIP_DCC_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_DCC_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_DCC_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_DCC_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_DI_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x4)//Ctrl enable of all interfaces belong to VIP's DI
#define VIP_LOGMODULE_VIP_DI_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_DI_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_DI_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_DI_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_GIBI_OD_DEBUG		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x5)//Ctrl enable of all interfaces belong to VIP's gibi OD
#define VIP_LOGMODULE_VIP_GIBI_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_GIBI_OD_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_GIBI_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_GIBI_OD_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_ICM_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x6)//Ctrl enable of all interfaces belong to VIP's ICM
#define VIP_LOGMODULE_VIP_ICM_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_ICM_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_ICM_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_ICM_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_LC_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x7)//Ctrl enable of all interfaces belong to VIP's Local contrast
#define VIP_LOGMODULE_VIP_LC_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_LC_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_LC_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_LC_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_LD_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x8)//Ctrl enable of all interfaces belong to VIP's Local dimming
#define VIP_LOGMODULE_VIP_LD_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_LD_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_LD_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_LD_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_NR_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x9)//Ctrl enable of all interfaces belong to VIP's nr
#define VIP_LOGMODULE_VIP_NR_info_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_NR_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_NR_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_NR_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_PCID_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0xa)//Ctrl enable of all interfaces belong to VIP's pcid
#define VIP_LOGMODULE_VIP_PCID_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PCID_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_PCID_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PCID_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_PEAKING_DEBUG 	VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0xb)//Ctrl enable of all interfaces belong to VIP's peaking
#define VIP_LOGMODULE_VIP_PEAKING_interface1_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PEAKING_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_PEAKING_interface7_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PEAKING_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_PQA_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0xc)//Ctrl enable of all interfaces belong to VIP's pq adaptive
#define VIP_LOGMODULE_VIP_PQA_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PQA_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_PQA_interface2_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PQA_DEBUG,0x2)
#define VIP_LOGMODULE_VIP_PQA_interface3_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PQA_DEBUG,0x3)
#define VIP_LOGMODULE_VIP_PQA_interface4_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PQA_DEBUG,0x4)
#define VIP_LOGMODULE_VIP_PQA_interface5_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PQA_DEBUG,0x5)
#define VIP_LOGMODULE_VIP_PQA_interface6_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PQA_DEBUG,0x6)
#define VIP_LOGMODULE_VIP_PQA_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_PQA_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_RPC_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0xd)//Ctrl enable of all interfaces belong to VIP's pq rpc
#define VIP_LOGMODULE_VIP_RPC_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_RPC_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_RPC_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_RPC_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_ScalerCtrl_DEBUG	VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0xe)//Ctrl enable of all interfaces belong to scaler/ctrl
#define VIP_LOGMODULE_VIP_ScalerCtrl_Color_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_ScalerCtrl_DEBUG,0x1)//scalerColorLib
#define VIP_LOGMODULE_VIP_ScalerCtrl_Rtice2ap_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_ScalerCtrl_DEBUG,0x2)//rtice2ap
#define VIP_LOGMODULE_VIP_ScalerColor_interface7_DEBUG	VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_ScalerCtrl_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_XC_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0xf)//Ctrl enable of all interfaces belong to VIP's xc
#define VIP_LOGMODULE_VIP_XC_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_XC_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_XC_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_XC_DEBUG,0x7)


#define VIP_LOGMODULE_VIP_V4L2_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x10)//Ctrl enable of all interfaces belong to VIP's V4L2
#define VIP_LOGMODULE_VIP_V4L2_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_V4L2_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_V4L2_interface2_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_V4L2_DEBUG,0x2)
#define VIP_LOGMODULE_VIP_V4L2_interface3_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_V4L2_DEBUG,0x3)
#define VIP_LOGMODULE_VIP_V4L2_interface4_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_V4L2_DEBUG,0x4)
#define VIP_LOGMODULE_VIP_V4L2_interface5_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_V4L2_DEBUG,0x5)
#define VIP_LOGMODULE_VIP_V4L2_interface6_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_V4L2_DEBUG,0x6)
#define VIP_LOGMODULE_VIP_V4L2_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_V4L2_DEBUG,0x7)


#define VIP_LOGMODULE_VIP_IP31_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x1f)
#define VIP_LOGMODULE_VIP_IP31_interface1_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_IP31_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_IP31_interface7_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_IP31_DEBUG,0x7)

#define VIP_LOGMODULE_VIP_TC_DEBUG 		VIP_LOGIP_DEFINE(VIP_LOGMODULE_VIP_DEBUG,0x1f)
#define VIP_LOGMODULE_VIP_TC_GENERAL_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_TC_DEBUG,0x1)
#define VIP_LOGMODULE_VIP_TC_METADATA_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_TC_DEBUG,0x2)
#define VIP_LOGMODULE_VIP_TC_ErrorStatus_DEBUG		VIP_LOGINTERFACE_DEFINE(VIP_LOGMODULE_VIP_TC_DEBUG,0x3)

/*print method*/
extern unsigned char gVipDebugLogCtrls[256];
extern unsigned int gDebugPrintDelayTime;
#define VIP_LOG_id2index(x)		(((x) >> 2) & 0xff)
#define VIP_LOG_id2bitOffset(x)		(((x) & 0x3) * 2)
#define VIP_LOG_CTRL(id) ((gVipDebugLogCtrls[VIP_LOG_id2index(id)] >> VIP_LOG_id2bitOffset(id)) & 0x3)
#define _VIPprintfPrivate(level,id,printCount,format,args...) \
{\
	unsigned char f = 0;\
	unsigned int tid = 0;\
	f = VIP_LOG_CTRL(0);\
	if(gDebugPrintDelayTime && (printCount % gDebugPrintDelayTime)){\
		f = 0;\
	}\
	if(f == 3){\
		tid = id & 0x300;\
		f = VIP_LOG_CTRL(tid);\
	}\
	if(f == 3){\
		tid = id & 0x3f8;\
		f = VIP_LOG_CTRL(tid);\
		if(f == 3){\
			f = VIP_LOG_CTRL(id);\
		}\
	}\
	tid = (id >> 8) & 0x3;\
	if(f == 1){ \
		if(tid == 1){\
			rtd_printk(KERN_EMERG,"MEMC_%3x",format,id,##args); \
		}else if(tid == 2){\
			rtd_printk(KERN_EMERG,"VGIP_%3x",format,id,##args); \
		}else{\
			rtd_printk(KERN_EMERG,"VIP_%3x",format,id,##args); \
		}\
	}else if(f == 3){	\
		if(tid == 1){\
			rtd_printk(level,"MEMC_%3x",format,id,##args); \
		}else if(tid == 2){\
			rtd_printk(level,"VGIP_%3x",format,id,##args); \
		}else{\
			rtd_printk(level,"VIP_%3x",format,id,##args); \
		}\
	}\
}
#define VIPprintfPrivate(level,id,format,args...) _VIPprintfPrivate(level,id,1,format,##args)
#define VIPprintf _VIPprintfPrivate

/* ROSprint for DI*/
#define ROSPrintf_DILv1(fmt, args...) VIPprintf(VIP_LOGLEVEL_DEBUG, VIP_LOGMODULE_VGIP_DI_interface1_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_DILv7(fmt, args...) VIPprintf(VIP_LOGLEVEL_DEBUG, VIP_LOGMODULE_VGIP_DI_interface7_DEBUG, MA_print_count, fmt, ##args)

/* ROSprint for PQA*/
#define ROSPrintf_INFO_PQA1(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_PQA_Info1_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_INFO_PQA2(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_PQA_Info2_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_INFO_PQA3(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_PQA_Info3_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_INFO_PQA4(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_PQA_Info4_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_INFO_PQA5(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_PQA_Info5_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_INFO_PQA6(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_PQA_Info6_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_INFO_PQA7(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_PQA_Info7_DEBUG, MA_print_count, fmt, ##args)

/* ROSprint for info calculation */
#define ROSPrintf_MadHist(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_CalInfo_MadHist_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_PQA_SPM(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_CalInfo_PQASPM_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_FMC_HMC(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_CalInfo_FMCHMC_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_YHueSat_Hist(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_CalInfo_YHueSatHist_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_BitRate_Ctrl(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_CalInfo_BitRate_Ctrl_DEBUG, MA_print_count, fmt, ##args)

/* ROSprint for info pattern */
#define ROSPrintf_ID_Pattern(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_ID_Number_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_ID_YHist(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_ID_YHist_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_ID_Hue(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_ID_Hue_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_ID_Sat(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_ID_Sat_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_ID_Identiy(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_ID_Identiy_DEBUG, MA_print_count, fmt, ##args)

/* ROSprint for DeContour */
#define ROSPrintf_Decontour_1(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_Decontour_1_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_Decontour_2(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_Decontour_2_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_Decontour_3(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_Decontour_3_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_Decontour_4(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_Decontour_4_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_Decontour_5(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_Decontour_5_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_Decontour_6(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_Decontour_6_DEBUG, MA_print_count, fmt, ##args)
#define ROSPrintf_Decontour_7(fmt, args...) VIPprintf(VIP_LOGLEVEL_INFO, VIP_LOGMODULE_VGIP_Decontour_7_DEBUG, MA_print_count, fmt, ##args)

#endif
