#ifndef __RTK_LSADC_DEV_H__
#define __RTK_LSADC_DEV_H__

#include <linux/kfifo.h>


#define RTK_LSADC_IOC_MAGIC            'o'
#define RTK_LSADC_GET_ADCVAL           _IOR(RTK_LSADC_IOC_MAGIC, 0, RTK_LSADC_VAL_T)
#define RTK_LSADC_SET_ACTIVE           _IOW(RTK_LSADC_IOC_MAGIC, 1, RTK_LSADC_VAL_T)
#define RTK_LSADC_SET_TRESHOLD         _IOR(RTK_LSADC_IOC_MAGIC, 2, RTK_LSADC_VAL_T)
#define RTK_LSADC_SET_SW               _IOW(RTK_LSADC_IOC_MAGIC, 3, RTK_LSADC_VAL_T)
#define RTK_LSADC_SET_MODE             _IOR(RTK_LSADC_IOC_MAGIC, 4, RTK_LSADC_VAL_T)
#define RTK_LSADC_GET_ACTIVE           _IOW(RTK_LSADC_IOC_MAGIC, 5, RTK_LSADC_VAL_T)
#define RTK_LSADC_GET_THRESHOLD        _IOW(RTK_LSADC_IOC_MAGIC, 6, RTK_LSADC_VAL_T)
#define RTK_LSADC_GET_SW               _IOR(RTK_LSADC_IOC_MAGIC, 7, RTK_LSADC_VAL_T)
#define RTK_LSADC_GET_MODE             _IOR(RTK_LSADC_IOC_MAGIC, 8, RTK_LSADC_VAL_T)
#define RTK_LSADC_DUMP                 _IOR(RTK_LSADC_IOC_MAGIC, 9, RTK_LSADC_VAL_T)

#endif
