/*
 * SHEIPA SPI controller driver
 *
 * Copyright 2015-2018, Realtek Semiconductor Corp.
 * Author: PSP Software Group
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef _SPI_SHEIPA_H
#define _SPI_SHEIPA_H

#define BFO_SPI_FLASH_CTRLR0_FAST_RD 20u
#define BFW_SPI_FLASH_CTRLR0_FAST_RD 1u
#define BFO_SPI_FLASH_CTRLR0_DATA_CH 18u
#define BFW_SPI_FLASH_CTRLR0_DATA_CH 2u
#define BFO_SPI_FLASH_CTRLR0_ADDR_CH 16u
#define BFW_SPI_FLASH_CTRLR0_ADDR_CH 2u
#define BFO_SPI_FLASH_CTRLR0_CFS 12u
#define BFW_SPI_FLASH_CTRLR0_CFS 3u
#define BFO_SPI_FLASH_CTRLR0_SRL 11u
#define BFW_SPI_FLASH_CTRLR0_SRL 1u
#define BFO_SPI_FLASH_CTRLR0_SLV_OE 10u
#define BFW_SPI_FLASH_CTRLR0_SLV_OE 1u
#define BFO_SPI_FLASH_CTRLR0_TMOD 8u
#define BFW_SPI_FLASH_CTRLR0_TMOD 2u
#define BFO_SPI_FLASH_CTRLR0_SCPOL 7u
#define BFW_SPI_FLASH_CTRLR0_SCPOL 1u
#define BFO_SPI_FLASH_CTRLR0_FRF 4u
#define BFW_SPI_FLASH_CTRLR0_FRF 2u
#define BFO_SPI_FLASH_CTRLR0_DFS 0u
#define BFW_SPI_FLASH_CTRLR0_DFS 4u
#define BFO_SPI_FLASH_CTRLR1_NDF 0u
#define BFW_SPI_FLASH_CTRLR1_NDF 16u
#define BFO_SPI_FLASH_SSIENR_SSI_EN 0u
#define BFW_SPI_FLASH_SSIENR_SSI_EN 1u
#define BFO_SPI_FLASH_MWCR_MHS 2u
#define BFW_SPI_FLASH_MWCR_MHS 1u
#define BFO_SPI_FLASH_MWCR_MDD 1u
#define BFW_SPI_FLASH_MWCR_MDD 1u
#define BFO_SPI_FLASH_MWCR_MWMOD 0u
#define BFW_SPI_FLASH_MWCR_MWMOD 1u
#define BFO_SPI_FLASH_SER 0u
#define BFW_SPI_FLASH_SER 4u
#define BFO_SPI_FLASH_BAUDR_SCKDV 0u
#define BFW_SPI_FLASH_BAUDR_SCKDV 16u
#define BFO_SPI_FLASH_TXFTLR_TFT 0u
#define BFW_SPI_FLASH_TXFTLR_TFT 3u
#define BFO_SPI_FLASH_RXFTLR_RFT 0u
#define BFW_SPI_FLASH_RXFTLR_RFT 3u
#define BFO_SPI_FLASH_TXFLR_TXTFL 0u
#define BFW_SPI_FLASH_TXFLR_TXTFL 3u
#define BFO_SPI_FLASH_RXFLR_RXTFL 0u
#define BFW_SPI_FLASH_RXFLR_RXTFL 3u
#define BFO_SPI_FLASH_SR_BUSY 0u
#define BFW_SPI_FLASH_SR_BUSY 1u
#define BFO_SPI_FLASH_SR_TFNF 1u
#define BFW_SPI_FLASH_SR_TFNF 1u
#define BFO_SPI_FLASH_SR_TFE 2u
#define BFW_SPI_FLASH_SR_TFE 1u
#define BFO_SPI_FLASH_SR_RFNE 3u
#define BFW_SPI_FLASH_SR_RFNE 1u
#define BFO_SPI_FLASH_SR_RFF 4u
#define BFW_SPI_FLASH_SR_RFF 1u
#define BFO_SPI_FLASH_SR_TXE 5u
#define BFW_SPI_FLASH_SR_TXE 1u
#define BFO_SPI_FLASH_SR_DCOL 6u
#define BFW_SPI_FLASH_SR_DCOL 1u
#define BFO_SPI_FLASH_IMR_TXEIM 0u
#define BFW_SPI_FLASH_IMR_TXEIM 1u
#define BFO_SPI_FLASH_IMR_TXOIM 1u
#define BFW_SPI_FLASH_IMR_TXOIM 1u
#define BFO_SPI_FLASH_IMR_RXUIM 2u
#define BFW_SPI_FLASH_IMR_RXUIM 1u
#define BFO_SPI_FLASH_IMR_RXOIM 3u
#define BFW_SPI_FLASH_IMR_RXOIM 1u
#define BFO_SPI_FLASH_IMR_RXFIM 4u
#define BFW_SPI_FLASH_IMR_RXFIM 1u
#define BFO_SPI_FLASH_IMR_FSEIM 5u
#define BFW_SPI_FLASH_IMR_FSEIM 1u
#define BFO_SPI_FLASH_IMR_WBEIM 6u
#define BFW_SPI_FLASH_IMR_WBEIM 1u
#define BFO_SPI_FLASH_IMR_BYEIM 7u
#define BFW_SPI_FLASH_IMR_BYEIM 1u
#define BFO_SPI_FLASH_IMR_ACTIM 8u
#define BFW_SPI_FLASH_IMR_ACTIM 1u
#define BFO_SPI_FLASH_IMR_TXEIM_PEND 9u
#define BFW_SPI_FLASH_IMR_TXEIM_PEND 1u
#define BFO_SPI_FLASH_ISR_TXEIS 0u
#define BFW_SPI_FLASH_ISR_TXEIS 1u
#define BFO_SPI_FLASH_ISR_TXOIS 1u
#define BFW_SPI_FLASH_ISR_TXOIS 1u
#define BFO_SPI_FLASH_ISR_RXUIS 2u
#define BFW_SPI_FLASH_ISR_RXUIS 1u
#define BFO_SPI_FLASH_ISR_RXOIS 3u
#define BFW_SPI_FLASH_ISR_RXOIS 1u
#define BFO_SPI_FLASH_ISR_RXFIS 4u
#define BFW_SPI_FLASH_ISR_RXFIS 1u
#define BFO_SPI_FLASH_ISR_FSEIS 5u
#define BFW_SPI_FLASH_ISR_FSEIS 1u
#define BFO_SPI_FLASH_ISR_WBEIS 6u
#define BFW_SPI_FLASH_ISR_WBEIS 1u
#define BFO_SPI_FLASH_ISR_BYEIS 7u
#define BFW_SPI_FLASH_ISR_BYEIS 1u
#define BFO_SPI_FLASH_ISR_ACTIS 8u
#define BFW_SPI_FLASH_ISR_ACTIS 1u
#define BFO_SPI_FLASH_ISR_TXEIS_PEND 9u
#define BFW_SPI_FLASH_ISR_TXEIS_PEND 1u
#define BFO_SPI_FLASH_RISR_TXEIR 0u
#define BFW_SPI_FLASH_RISR_TXEIR 1u
#define BFO_SPI_FLASH_RISR_TXOIR 1u
#define BFW_SPI_FLASH_RISR_TXOIR 1u
#define BFO_SPI_FLASH_RISR_RXUIR 2u
#define BFW_SPI_FLASH_RISR_RXUIR 1u
#define BFO_SPI_FLASH_RISR_RXOIR 3u
#define BFW_SPI_FLASH_RISR_RXOIR 1u
#define BFO_SPI_FLASH_RISR_RXFIR 4u
#define BFW_SPI_FLASH_RISR_RXFIR 1u
#define BFO_SPI_FLASH_RISR_FSEIR 5u
#define BFW_SPI_FLASH_RISR_FSEIR 1u
#define BFO_SPI_FLASH_RISR_WBEIR 6u
#define BFW_SPI_FLASH_RISR_WBEIR 1u
#define BFO_SPI_FLASH_RISR_BYEIR 7u
#define BFW_SPI_FLASH_RISR_BYEIR 1u
#define BFO_SPI_FLASH_RISR_ACTIR 8u
#define BFW_SPI_FLASH_RISR_ACTIR 1u
#define BFO_SPI_FLASH_TXOICR_TXOICR 0u
#define BFW_SPI_FLASH_TXOICR_TXOICR 1u
#define BFO_SPI_FLASH_RXOICR_RXOICR 0u
#define BFW_SPI_FLASH_RXOICR_RXOICR 1u
#define BFO_SPI_FLASH_RXUICR_RXUICR 0u
#define BFW_SPI_FLASH_RXUICR_RXUICR 1u
#define BFO_SPI_FLASH_MSTICR_MSTICR 0u
#define BFW_SPI_FLASH_MSTICR_MSTICR 1u
#define BFO_SPI_FLASH_ICR_ICR 0u
#define BFW_SPI_FLASH_ICR_ICR 1u
#define BFO_SPI_FLASH_DMACR_RDMAE 0u
#define BFW_SPI_FLASH_DMACR_RDMAE 1u
#define BFO_SPI_FLASH_DMACR_TDMAE 1u
#define BFW_SPI_FLASH_DMACR_TDMAE 1u
#define BFO_SPI_FLASH_DMATDLR_DMATDL 0u
#define BFW_SPI_FLASH_DMATDLR_DMATDL 3u
#define BFO_SPI_FLASH_DMARDLR_DMARDL 0u
#define BFW_SPI_FLASH_DMARDLR_DMARDL 3u
#define BFO_SPI_FLASH_AUTO_LEN_ADDR 16u
#define BFW_SPI_FLASH_AUTO_LEN_ADDR 2u
#define BFO_SPI_FLASH_AUTO_LEN_DUM 0u
#define BFW_SPI_FLASH_AUTO_LEN_DUM 16u

int sheipa_spi_config(struct spi_device *spi, struct spi_nor *nor);
#endif
