#KBUILD_CFLAGS += -Wall -Werror

realtek_delivery-objs = rtkdelivery_driver.o \
					rtkdelivery.o \
					rtkdelivery_debug.o \
					rtkdelivery_ioctl.o \
					rtkdelivery_ioctl_Delivery.o

obj-y += realtek_delivery.o

