#
# Makefile for the linux kernel.
#
KBUILD_CFLAGS += -Werror
#KBUILD_CPPFLAGS += -I drivers/rtk_kdriver/include/
#KBUILD_CPPFLAGS += -I drivers/rtk_kdriver/include/rtk_kdriver
#KBUILD_CPPFLAGS += -I drivers/rtk_kdriver/ir/inc
#KBUILD_CPPFLAGS += -I drivers/rtk_kdriver
# Inpute device
obj-$(CONFIG_RTK_DCCTI_DRV) += rtk_dccti_drv.o
