KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod
KBUILD_CPPFLAGS  += -I drivers/rtk_kdriver/demod/demodcomm

demodcore-objs := foundation.o \
					math_mpi.o \
					atsc_demod_rtk_r_base.o \
					atsc_demod_rtk_r.o \
					isdbt_demod_rtk_r_base.o \
					isdbt_demod_rtk_r.o \
					qam_demod_rtk_r_base.o \
					qam_demod_rtk_r.o \
					dvbtx_demod_rtk_a_base.o \
					dvbtx_demod_rtk_a.o \
					dvbtx_rom_data.o \
					dvbsx_demod_rtk_a.o \
					dvbsx_demod_rtk_a_base.o \
					dvbsx_blindscan_demod_rtk_a.o \
					dvbsx_rom_data.o \
					diseqc_rtk.o \
					dtmb_demod_base.o \
					dtmb_demod_rtk.o \
					dtmb_demod_rtk_user.o \
					ifd_new.o \
					ifd_agc.o \
					ifd_cr.o \
					ifd_video.o \
					ifd_table.o \
					ifd_analog.o \

obj-y += demodcore.o 



