#
# Makefile for the linux kernel.
#
KBUILD_CFLAGS += -Werror
KBUILD_CPPFLAGS += -I drivers/rtk_kdriver/include/
KBUILD_CPPFLAGS += -I drivers/rtk_kdriver/include/rtk_kdriver
KBUILD_CPPFLAGS += -I drivers/rtk_kdriver/ir/inc
KBUILD_CPPFLAGS += -I drivers/rtk_kdriver
# Inpute device
obj-y += ir_table_default.o
obj-y += ir_table_others.o
obj-y += ir_table_user.o
obj-y += ir_table_tv001.o
obj-y += ir_table_tv002.o
obj-y += ir_table_tv010.o
obj-y += ir_table_tv005.o
obj-y += ir_table_tv013.o
obj-y += ir_table_tv015.o
obj-y += ir_table_tv030.o
obj-y += ir_table_tv035.o
obj-y += ir_table_tv036.o
obj-y += ir_table_tv051.o
KBUILD_CFLAGS += -Werror
