KBUILD_CPPFLAGS += -I ./
obj-y += rtk_otp_util.o rtk_otp_hw.o rtk_otp_dev.o rtk_otp_ecc_algorithm.o \
									rtk_otp_region.o rtk_otp_region_api.o
									
obj-$(CONFIG_RTK_KDRV_HDCP_KEY_FROM_OTP) += rtk_otp_hdcp_util.o
