#
# Makefile for the linux kernel.
#
KBUILD_CFLAGS += -Werror
obj-$(CONFIG_ARCH_RTK299O) += rtk_crt-rtd299o.o
obj-$(CONFIG_ARCH_RTK289X) += rtk_crt-rtd289x.o
obj-$(CONFIG_ARCH_RTK284X) += rtk_crt-rtd284x.o
obj-$(CONFIG_ARCH_RTK287X) += rtk_crt-rtd287x.o
obj-$(CONFIG_ARCH_RTK285X) += rtk_crt-rtd285x.o
obj-$(CONFIG_ARCH_RTK285O) += rtk_crt-rtd285o.o
obj-y += rtk_crt-rtd288o.o
