#ifndef _VPQ_CMD_ID_H_
#define _VPQ_CMD_ID_H_

/************************************************************************
 *  Include files
 ************************************************************************/
//#include "vpq/vpq_type.h"
#include "../ai/ai_cmd_id.h"

/************************************************************************
 *  Definitions
 ************************************************************************/
#define VPQ_DEVICE_NAME						"vpqdev"
#define VPQ_IOC_MAGIC 'p'

#define DOLBY_DEVICE_NAME						"dolbyvisionEDR0"
#define DOLBY_IOC_MAGIC 'd'

enum vpq_ioc_pq_cmd
{
	VPQ_IOC_PQ_CMD_INIT = 0,
	VPQ_IOC_PQ_CMD_UNINIT = 1,// 1
	VPQ_IOC_PQ_CMD_OPEN = 2,// 2
	VPQ_IOC_PQ_CMD_CLOSE = 3,// 3
	VPQ_IOC_PQ_CMD_SET_COLOR_TEMP = 4,
	VPQ_IOC_PQ_CMD_GET_MOTION_LEVEL = 5,
	VPQ_IOC_PQ_CMD_GET_NOISE_LEVEL = 6,
	VPQ_IOC_PQ_CMD_SET_GAMMA_LUT = 7,
	VPQ_IOC_PQ_CMD_SET_SPLIT_DEMO = 8,
	VPQ_IOC_PQ_CMD_SET_IRE_INNER_PATTERN = 9,
	VPQ_IOC_PQ_CMD_SET_FILM_MODE = 10,
	VPQ_IOC_PQ_CMD_SET_FILM_TABLE = 11,
	VPQ_IOC_PQ_CMD_SET_SHARPNESS_LEVEL = 12,
	VPQ_IOC_PQ_CMD_SET_SHARPNESS_TABLE = 13,
	VPQ_IOC_PQ_CMD_NR_PQA_TABLE = 14,
	VPQ_IOC_PQ_CMD_NR_PQA_INPUT_TABLE = 15,
	VPQ_IOC_PQ_CMD_NR_LEVEL = 16,
	VPQ_IOC_PQ_CMD_MPEGNR_LEVEL = 17,
	VPQ_IOC_PQ_CMD_GET_HistoData_Countbins = 18,
	VPQ_IOC_PQ_CMD_GET_HistoData_APL = 19,
	VPQ_IOC_PQ_CMD_GET_HistoData_Min = 20,
	VPQ_IOC_PQ_CMD_GET_HistoData_Max = 21,
	VPQ_IOC_PQ_CMD_GET_HistoData_PeakLow = 22,
	VPQ_IOC_PQ_CMD_GET_HistoData_PeakHigh = 23,
	VPQ_IOC_PQ_CMD_SET_FreshContrast = 24,
	VPQ_IOC_PQ_CMD_SET_FreshContrastLUT = 25,
	VPQ_IOC_PQ_CMD_GET_FreshContrastBypassLUT = 26,
	VPQ_IOC_PQ_CMD_SET_ColorGain = 27,
	VPQ_IOC_PQ_CMD_SET_CLEAR_WHITE = 28,
	VPQ_IOC_PQ_CMD_SET_INIT_COLOR_ADV = 29,
	VPQ_IOC_PQ_CMD_SET_INIT_COLOR_EXP = 30,
	VPQ_IOC_PQ_CMD_SET_FRESH_COLOR = 31,
	VPQ_IOC_PQ_CMD_SET_PREFERRED_COLOR = 32,
	VPQ_IOC_PQ_CMD_SET_COLOR_MANAGEMENT = 33,
	VPQ_IOC_PQ_CMD_SET_Pic_Ctrl = 34,
	VPQ_IOC_PQ_CMD_SET_Black_Level = 35,
	VPQ_IOC_PQ_CMD_GET_HistoData_chrm_bin =36,
	VPQ_IOC_PQ_CMD_GET_HistoData_hue_bin =37,
	VPQ_IOC_PQ_CMD_GET_HistoData_skin_count =38,
	VPQ_IOC_PQ_CMD_GET_HistoData_sat_status =39,
	VPQ_IOC_PQ_CMD_GET_HistoData_diff_sum =40,
	VPQ_IOC_PQ_CMD_GET_HistoData_texture =41,
	VPQ_IOC_PQ_CMD_GET_HistoData_motion =42,
	VPQ_IOC_PQ_CMD_SET_COLOR_GAMUT = 43,
	VPQ_IOC_PQ_CMD_SET_SAT_LUT = 44,
	VPQ_IOC_PQ_CMD_SET_FILM_FPS = 45,
	VPQ_IOC_PQ_CMD_SET_DITHER_BIT = 46,
	VPQ_IOC_PQ_CMD_GET_Input_V_Freq = 47,
	VPQ_IOC_PQ_CMD_SET_VPQ_Shp_Val = 48,
	VPQ_IOC_PQ_CMD_SET_PROJECT_ID = 49,
	VPQ_IOC_PQ_CMD_SET_ICM_ELEM = 50,
	VPQ_IOC_PQ_CMD_SET_SR_TABLE = 51,
	VPQ_IOC_PQ_CMD_SET_GAMUT_3D_LUT_N9_BUFFER = 52,
	VPQ_IOC_PQ_CMD_SET_GAMUT_3D_LUT_N17_BUFFER = 53,
	VPQ_IOC_PQ_CMD_SET_GAMUT_3D_LUT_INDEX = 54,
	VPQ_IOC_PQ_CMD_SET_HDR_GAMUTMATRIX = 55,
	VPQ_IOC_PQ_CMD_SET_HDR_3DLUT = 56,
	VPQ_IOC_PQ_CMD_SET_LOWDEALY_MODE = 57,
	VPQ_IOC_PQ_CMD_SET_HDR_3DLUT_16 = 58,
	VPQ_IOC_PQ_CMD_NR_INPUT = 59,
	VPQ_IOC_PQ_CMD_SET_HDR_3DLUT_24x24x24_16_1 = 60,
	VPQ_IOC_PQ_CMD_SET_HDR_3DLUT_24x24x24_16_2 = 61,
	VPQ_IOC_PQ_CMD_SET_HDR_Eotf = 62,
	VPQ_IOC_PQ_CMD_SET_HDR_Oetf = 63,
	VPQ_IOC_PQ_CMD_GET_HDR_PicInfo = 64,
	VPQ_IOC_PQ_CMD_SET_HDR_InvGamma = 65,
	VPQ_IOC_PQ_CMD_SET_BLUE_STRETCH = 66,
	VPQ_IOC_PQ_CMD_SET_PQModeInfo = 67,
	VPQ_IOC_PQ_CMD_SET_LOCALCONTRAST_PARAM = 68,
	VPQ_IOC_PQ_CMD_SET_OdExtentions = 69,
	VPQ_IOC_PQ_CMD_SET_Od = 70,
	VPQ_IOC_PQ_CMD_SET_DeMura = 71,
        VPQ_IOC_PQ_CMD_SET_COLOR_FILTER = 72,
        VPQ_IOC_PQ_CMD_SET_Decontour = 73,
	VPQ_IOC_PQ_CMD_SET_AIinfo = 74,
	VPQ_IOC_PQ_CMD_GET_AI_PA = 75,
	//VPQ_IOC_PQ_CMD_SET_COLOR_FILTER = 76,
	VPQ_IOC_PQ_CMD_SET_3D_COLOR_CORRECTION = 76,
	VPQ_IOC_PQ_CMD_SET_EDGE_ENHANCE = 77,
	VPQ_IOC_PQ_CMD_HDR_DEMO_Mode_ON = 78,
	VPQ_IOC_PQ_CMD_HDR_DEMO_Mode_OFF = 79,
	VPQ_IOC_PQ_CMD_SET_PCID = 80,
	VPQ_IOC_PQ_CMD_SET_LMMH_DeMura = 81,
	VPQ_IOC_PQ_CMD_GET_GENRE_LABELS = 82,
	VPQ_IOC_PQ_CMD_AI_DETECTION_ON = 83,
	VPQ_IOC_PQ_CMD_AI_DETECTION_OFF = 84,
	VPQ_IOC_PQ_CMD_GET_AI_MODE = 85,
	VPQ_IOC_PQ_CMD_GET_SCENE_PROB = 86,
};

typedef struct {
	char labels[AI_SCENE_TYPE_NUM][50];
	int in_label_num;
	int out_label_num;
} AI_SCENE_LABEL_T;

#define VPQ_IOC_INIT						_IO(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_INIT)
#define VPQ_IOC_UNINIT						_IO(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_UNINIT)
#define VPQ_IOC_OPEN						_IO(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_OPEN)
#define VPQ_IOC_CLOSE						_IO(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_CLOSE)
#define VPQ_IOC_SET_COLOR_TEMP				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_COLOR_TEMP, COLORTEMP_ELEM_T)
#define VPQ_IOC_SET_COLOR_FILTER			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_COLOR_FILTER, unsigned int)
#define VPQ_IOC_GET_MOTION_LEVEL			_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_MOTION_LEVEL, unsigned int)
#define VPQ_IOC_GET_NOISE_LEVEL				_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_NOISE_LEVEL, unsigned int)
#define VPQ_IOC_SET_GAMMA_LUT				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_GAMMA_LUT, GAMMA_RGB_T)
#define VPQ_IOC_SET_SPLIT_DEMO				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_SPLIT_DEMO, unsigned int)
#define VPQ_IOC_SET_IRE_INNER_PATTERN		_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_IRE_INNER_PATTERN, unsigned int)
#define VPQ_IOC_SET_FILM_MODE				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_FILM_MODE, DRV_film_mode)
#define VPQ_IOC_SET_FILM_TABLE				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_FILM_TABLE, DRV_film_table_t)
#define VPQ_IOC_SET_SHARPNESS_LEVEL			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_SHARPNESS_LEVEL, DRV_Sharpness_Level)
#define VPQ_IOC_SET_SHARPNESS_TABLE			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_SHARPNESS_TABLE, unsigned int)
#define VPQ_IOC_SET_VPQ_Shp_Val		_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_VPQ_Shp_Val, unsigned short)
#define VPQ_IOC_SET_EDGE_ENHANCE		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_EDGE_ENHANCE, unsigned int)
#define VPQ_IOC_SET_NR_PQA_TABLE			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_NR_PQA_TABLE, unsigned char)
#define VPQ_IOC_SET_NR_PQA_INPUT_TABLE		_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_NR_PQA_INPUT_TABLE, unsigned char)
#define VPQ_IOC_SET_NR_LEVEL 				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_NR_LEVEL, unsigned int)
#define VPQ_IOC_SET_MPEGNR_LEVEL 			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_MPEGNR_LEVEL, unsigned int)
#define VPQ_IOC_GET_HistoData_Countbins		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_Countbins, FreshContrastBin_T)
#define VPQ_IOC_GET_HistoData_chrm_bin		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_chrm_bin, chrm_bin_T)
#define VPQ_IOC_GET_HistoData_hue_bin		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_hue_bin, hue_bin_T)
#define VPQ_IOC_GET_HistoData_APL			_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_APL, unsigned int)
#define VPQ_IOC_GET_HistoData_Min			_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_Min, signed int)
#define VPQ_IOC_GET_HistoData_Max			_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_Max, signed int)
#define VPQ_IOC_GET_HistoData_PeakLow		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_PeakLow, signed int)
#define VPQ_IOC_GET_HistoData_PeakHigh		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_PeakHigh, signed int)
#define VPQ_IOC_GET_HistoData_skin_count	_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_skin_count, unsigned int)
#define VPQ_IOC_GET_HistoData_sat_status	_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_sat_status, unsigned int)
#define VPQ_IOC_GET_HistoData_diff_sum		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_diff_sum, unsigned int)
#define VPQ_IOC_GET_HistoData_motion		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_motion, unsigned int)
#define VPQ_IOC_GET_HistoData_texture  		_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HistoData_texture, unsigned int)
#define VPQ_IOC_SET_FreshContrast			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_FreshContrast, CHIP_DCC_T)
#define VPQ_IOC_SET_FreshContrastLUT		_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_FreshContrastLUT, FreshContrastLUT_T)
#define VPQ_IOC_GET_FreshContrastBypassLUT	_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_FreshContrastBypassLUT, FreshContrastLUT_T)
#define VPQ_IOC_SET_ColorGain				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_ColorGain, RTK_COLOR_GAIN_T)
#define VPQ_IOC_SET_CLEAR_WHITE 			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_CLEAR_WHITE, HAL_VPQ_CLEAR_WHITE)
#define VPQ_IOC_SET_INIT_COLOR_ADV			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_INIT_COLOR_ADV, unsigned int)
#define VPQ_IOC_SET_INIT_COLOR_EXP			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_INIT_COLOR_EXP, unsigned int)
#define VPQ_IOC_SET_FRESH_COLOR			_IOWR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_FRESH_COLOR, unsigned int)
#define VPQ_IOC_SET_PREFERRED_COLOR			_IOWR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_PREFERRED_COLOR, unsigned int)
#define VPQ_IOC_SET_COLOR_MANAGEMENT		_IOWR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_COLOR_MANAGEMENT, unsigned int)
#define VPQ_IOC_SET_3D_COLOR_CORRECTION		_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_3D_COLOR_CORRECTION, unsigned int)
#define VPQ_IOC_SET_PIC_CTRL 				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_Pic_Ctrl, VPQ_SetPicCtrl_T)
#define VPQ_IOC_SET_BLACK_LEVEL 			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_Black_Level, HAL_VPQ_SET_BLACK_LEVEL)
#define VPQ_IOC_SET_COLOR_GAMUT				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_COLOR_GAMUT, COLOR_GAMUT_T)
#define VPQ_IOC_SET_SAT_LUT					_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_SAT_LUT, VPQ_SAT_LUT_T)
#define VPQ_IOC_SET_FILM_FPS				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_FILM_FPS, unsigned int)
#define VPQ_IOC_SET_DITHER_BIT				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_DITHER_BIT, unsigned int)
#define VPQ_IOC_GET_Input_V_Freq			_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_Input_V_Freq, unsigned int)
#define VPQ_IOC_SET_PROJECT_ID				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_PROJECT_ID, unsigned int)
#define VPQ_IOC_SET_ICM_ELEM				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_ICM_ELEM, unsigned int)
#define VPQ_IOC_SET_SR_TABLE				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_SR_TABLE, unsigned int)
#define VPQ_IOC_SET_GAMUT_3D_LUT_N9_BUFFER			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_GAMUT_3D_LUT_N9_BUFFER, unsigned int)
#define VPQ_IOC_SET_GAMUT_3D_LUT_N17_BUFFER			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_GAMUT_3D_LUT_N17_BUFFER, unsigned int)
#define VPQ_IOC_SET_GAMUT_3D_LUT_INDEX			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_GAMUT_3D_LUT_INDEX, unsigned int)
#define VPQ_IOC_SET_HDR_GAMUTMATRIX	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_GAMUTMATRIX, HDR_SetGamut33Matrix_T)
#define VPQ_IOC_SET_HDR_3DLUT		_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_3DLUT, int)
#define VPQ_IOC_SET_LOWDELAY_MODE		_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_LOWDEALY_MODE,unsigned int)
#define VPQ_IOC_SET_HDR_3DLUT_16	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_3DLUT_16, int)
#define VPQ_IOC_HDR_DEMO_Mode_ON	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_HDR_DEMO_Mode_ON, int)
#define VPQ_IOC_HDR_DEMO_Mode_OFF	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_HDR_DEMO_Mode_OFF, int)
#define VPQ_IOC_SET_NR_INPUT	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_NR_INPUT, unsigned char)
#define VPQ_IOC_SET_HDR_3DLUT_24x24x24_16_1	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_3DLUT_24x24x24_16_1, int)
#define VPQ_IOC_SET_HDR_3DLUT_24x24x24_16_2	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_3DLUT_24x24x24_16_2, int)
#define VPQ_IOC_SET_HDR_Eotf	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_Eotf, int)
#define VPQ_IOC_SET_HDR_Oetf	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_Oetf, int)
#define VPQ_IOC_GET_HDR_PicInfo	_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_HDR_PicInfo, int)
#define VPQ_IOC_SET_HDR_InvGamma	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_HDR_InvGamma, unsigned char)
#define VPQ_IOC_SET_BLUE_STRETCH 			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_BLUE_STRETCH, unsigned int)
#define VPQ_IOC_SET_PQModeInfo	_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_PQModeInfo, int)
#define VPQ_IOC_SET_LOCALCONTRAST_PARAM			_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_LOCALCONTRAST_PARAM, CHIP_LOCAL_CONTRAST_T)
#define VPQ_IOC_SET_OdExtentions  _IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_OdExtentions, _HAL_VPQ_DATA_T)
#define VPQ_IOC_SET_PCID  _IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_PCID, _HAL_VPQ_DATA_T)
#define VPQ_IOC_SET_Od _IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_Od, _HAL_VPQ_DATA_T)
#define VPQ_IOC_SET_LMMH_DeMura  _IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_LMMH_DeMura, _HAL_VPQ_DATA_T)
#define VPQ_IOC_SET_DeMura  _IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_DeMura, _HAL_VPQ_DATA_T)
//#define VPQ_IOC_SET_COLOR_FILTER  _IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_COLOR_FILTER, unsigned int)
#define VPQ_IOC_SET_Decontour  _IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_Decontour, unsigned int)
#define VPQ_IOC_SET_AIinfo  				_IOW(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_SET_AIinfo, int)
#define VPQ_IOC_SET_AI_PA  				_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_AI_PA, unsigned int)
#define VPQ_IOC_GET_GENRE_LABELS			_IOWR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_GENRE_LABELS, AI_SCENE_LABEL_T)
#define VPQ_IOC_GET_AI_MODE                            _IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_AI_MODE, unsigned char)
#define VPQ_IOC_AI_DETECTION_ON	                        _IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_AI_DETECTION_ON, unsigned int)
#define VPQ_IOC_AI_DETECTION_OFF			_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_AI_DETECTION_OFF, unsigned int)
#define VPQ_IOC_GET_SCENE_PROB				_IOR(VPQ_IOC_MAGIC, VPQ_IOC_PQ_CMD_GET_SCENE_PROB, unsigned int)

#endif	/* _VPQ_CMD_ID_H_ */
