#ifndef _VPQ_LED_CMD_ID_H_
#define _VPQ_LED_CMD_ID_H_

/************************************************************************
 *  Definitions
 ************************************************************************/
#define VPQ_LED_DEVICE_NAME						"vpqleddev"
#define VPQ_LED_IOC_MAGIC 'l'

enum vpq_led_ioc_cmd
{
	VPQ_LED_CMD_INIT = 0,
	VPQ_LED_CMD_UNINIT = 1,
	VPQ_LED_CMD_SET_LD_INIT = 2,
	VPQ_LED_CMD_SET_LDEnable = 3,
	VPQ_LED_CMD_SET_LDSetLUT = 4,
	VPQ_LED_CMD_SET_LDEnablePixelCompensation = 5,
	VPQ_LED_CMD_SET_LDCtrlDemoMode = 6,
	VPQ_LED_CMD_SET_LDCtrlSPI = 7,
	VPQ_LED_CMD_LDGetAPL = 8,
	VPQ_LED_CMD_LDSetDBLUT = 9,
	VPQ_LED_CMD_LDSetDutyLimit = 10,
	VPQ_LED_CMD_LDSetDuty = 11,
	
	VPQ_LED_CMD_SET_SLR_VIP_TABLE_LD = 12,
	VPQ_LED_CMD_SET_SLR_VIP_TABLE_BLPF = 13,
	VPQ_LED_CMD_SET_SLR_VIP_TABLE_LDCOMP = 14,
	VPQ_LED_CMD_SET_LDSPI_SRAM_Data = 15,
};

#define VPQ_LED_IOC_INIT								_IO(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_INIT)
#define VPQ_LED_IOC_UNINIT								_IO(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_UNINIT)
#define VPQ_LED_IOC_SET_LD_INIT							_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_LD_INIT, KADP_LED_PANEL_INFO_T)
#define VPQ_LED_IOC_SET_LDEnable						_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_LDEnable, bool)
#define VPQ_LED_IOC_SET_LDSetLUT						_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_LDSetLUT, UINT8)
#define VPQ_LED_IOC_SET_LDEnablePixelCompensation		_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_LDEnablePixelCompensation, bool)
#define VPQ_LED_IOC_SET_LDCtrlDemoMode					_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_LDCtrlDemoMode, DRV_HAL_VPQ_LED_LDCtrlDemoMode)
#define VPQ_LED_IOC_SET_LDCtrlSPI					_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_LDCtrlSPI, UINT8)
#define VPQ_LED_IOC_LDGetAPL						_IOR(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_LDGetAPL, UINT16)
#define VPQ_LED_IOC_LDSetDBLUT						_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_LDSetDBLUT, KADP_LED_DB_LUT_T)
#define VPQ_LED_IOC_LDSetDutyLimit						_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_LDSetDutyLimit, UINT16)
#define VPQ_LED_IOC_LDSetDuty						_IOW(VPQ_LED_IOC_MAGIC,VPQ_LED_CMD_LDSetDuty , UINT16)
#define VPQ_LED_IOC_SET_SLR_VIP_TABLE_LD  			_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_SLR_VIP_TABLE_LD, DRV_Local_Dimming_Table)
#define VPQ_LED_IOC_SET_SLR_VIP_TABLE_BLPF  		_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_SLR_VIP_TABLE_BLPF, SLR_VIP_TABLE_BLPF)
#define VPQ_LED_IOC_SET_SLR_VIP_TABLE_LDCOMP  		_IOW(VPQ_LED_IOC_MAGIC, VPQ_LED_CMD_SET_SLR_VIP_TABLE_LDCOMP, DRV_LD_Data_Compensation_NewMode_2DTable)
#define VPQ_LED_IOC_SET_LDSPI_SRAM_Data				_IOW(VPQ_LED_IOC_MAGIC,VPQ_LED_CMD_SET_LDSPI_SRAM_Data , DRV_LD_LDSPI_DATASRAM_TYPE)

#endif	/* _VPQ_MEMC_LED_ID_H_ */
