#ifndef _VPQ_EXTERN_CMD_ID_H_
#define _VPQ_EXTERN_CMD_ID_H_

/************************************************************************
 *  Include files
 ************************************************************************/
//#include "vpq/vpq_extern_type.h"

/************************************************************************
 *  IO_CTRL Definitions
 ************************************************************************/
#define VPQ_EXTERN_DEVICE_NAME						"vpqexdev"
#define VPQ_EXTERN_IOC_MAGIC_ENG_MENU 'e'
#define VPQ_EXTERN_IOC_MAGIC 'q'						//Formal, TV001
#define VPQ_EXTERN_IOC_MAGIC_2 'Q'						//Formal, TV001
#define VPQ_EXTERN_IOC_MAGIC_TV002 'S'					//TV002
#define VPQ_EXTERN_IOC_MAGIC_TV030 'T'					//TV030
#define VPQ_EXTERN_IOC_MAGIC_TV040 'P'					//PANA
#define VPQ_EXTERN_IOC_MAGIC_TV043 'r'

typedef struct _HAL_VPQ_DATA_EXTERN_T{
    unsigned int version;
    unsigned int length;
    unsigned char wId;
    unsigned int pData;
} HAL_VPQ_DATA_EXTERN_T;

enum vpq_extend_ioc_pq_cmd
{
	VPQ_EXTERN_IOC_PQ_CMD_INIT = 0,
	VPQ_EXTERN_IOC_PQ_CMD_UNINIT = 1,/* 1*/
	VPQ_EXTERN_IOC_PQ_CMD_OPEN = 2,/* 2*/
	VPQ_EXTERN_IOC_PQ_CMD_CLOSE = 3,/* 3*/
	VPQ_EXTERN_IOC_PQ_CMD_INIT_PRJ_ID = 4,

	VPQ_EXTERN_IOC_PQ_CMD_SET_VGA_ADCGainOffset = 10,
	VPQ_EXTERN_IOC_PQ_CMD_SET_YPBPR_ADCGainOffset = 11,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE_CUSTOM_TV001 = 12,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE = 13,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA = 14,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_defaultPictureModeSet = 15,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_DolbyHDRPictureModeSet = 16,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType = 17,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultSDColorData = 18,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultHDColorData = 19,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA = 20,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA_defColorTempSet = 21,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType = 22,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_defaultColorFacMode = 23,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_AvColorFacMode = 24,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_YppColorFacMode = 25,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_VgaColorFacMode = 26,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiColorFacMode = 27,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiSDColorFacMode = 28,
	VPQ_EXTERN_IOC_PQ_CMD_REGISTER_NEW_VIPTABLE = 29,
	VPQ_EXTERN_IOC_PQ_CMD_GET_CUR_SRC_FMT = 30,
	VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_TIMING = 31,
	VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacMode_EXTERN = 32,
	VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_RESYNC = 33,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_SRC_RESYNC = 34,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_HANDLER_RESET = 35,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OD_SETTING_TABLE = 36,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OD_TABLE = 37,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OD_TABLE_TEST = 38,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DeMura = 39,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VALC = 40,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VALCprotectSetting = 41,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LEDOutGamma = 42,
	VPQ_EXTERN_IOC_PQ_CMD_SET_Output_InvOutput_Gamma = 43,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TCON_ENABLE_CTRL = 44,

	VPQ_EXTERN_IOC_PQ_CMD_GET_BRIGHTNESS = 50,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS = 51,
	VPQ_EXTERN_IOC_PQ_CMD_GET_CONTRAST = 52,
	VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST = 53,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SATURATION = 54,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SATURATION = 55,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HUE = 56,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HUE = 57,
	VPQ_EXTERN_IOC_PQ_CMD_GET_NR = 58,
	VPQ_EXTERN_IOC_PQ_CMD_SET_NR = 59,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SHARPNESS = 60,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SHARPNESS_EXTERN = 61,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DE_BLOCKING = 62,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DE_BLOCKING = 63,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DE_RINGING = 64,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DE_RINGING = 65,
	VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_TEMP = 66,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_EXTERN = 67,
	VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_GAIN = 68,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_GAIN_EXTERN = 69,
	VPQ_EXTERN_IOC_PQ_CMD_GET_FLESH_TONE = 70,
	VPQ_EXTERN_IOC_PQ_CMD_SET_FLESH_TONE = 71,
	VPQ_EXTERN_IOC_PQ_CMD_GET_BACKLIGHT = 72,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BACKLIGHT = 73,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PANEL_BL = 74,
	VPQ_EXTERN_IOC_PQ_CMD_GET_GAMMA_NUM = 75,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA = 76,
	VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_MODULE = 77,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_MODULE = 78,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEMO = 79,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_MODE = 80,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_MODE = 81,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HISTOGRAM = 82,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SR_LEVEL = 83,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SR_LEVEL = 84,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BLACK_PATTERN_OUTPUT = 85,
	VPQ_EXTERN_IOC_PQ_CMD_SET_WHITE_PATTERN_OUTPUT = 86,
	VPQ_EXTERN_IOC_PQ_CMD_GET_OD_LEVEL = 87,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OD_READ_ENABLE =88,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SRC_HDR_INFO =89,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SDR2HDR =90,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SDR2HDR =91,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_TYPE =92,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DCI_TYPE =93,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBY_HDR_PIC_MODE =94,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBY_HDR_PIC_MODE = 95,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR10_ENABLE = 96,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDR10_ENABLE = 97,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_LOG_ENABLE = 98,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DREAM_PANEL_BACKLIGHT = 99,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_BACKLIGHT = 100,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DCC_MODE = 101,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_MODE = 102,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ICM_TBL_IDX = 103,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_TBL_IDX = 104,
	VPQ_EXTERN_IOC_PQ_CMD_GET_FILM_MODE = 105,
	VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_MODE = 106,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDMI_CSC_DATA_RANGE_MODE = 107,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_CSC_DATA_RANGE_MODE = 108,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_FORCE_MODE = 109,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDR_FORCE_MODE = 110,
	VPQ_EXTERN_IOC_PQ_CMD_GET_CINEMA_PIC_MODE = 111,
	VPQ_EXTERN_IOC_PQ_CMD_SET_CINEMA_PIC_MODE = 112,
	VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_BYPASS_LV = 113,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_BYPASS_LV = 114,
	VPQ_EXTERN_IOC_PQ_CMD_GET_GDBC_MODE = 115,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GDBC_MODE = 116,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DCR_BACKLIGHT = 117,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VDPQ_MEM_ENABLE = 118,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HISTODATA_APL	= 119,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PANORAMA_TYPE = 120,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OUTGAMMA_SCURVE = 121,
	VPQ_EXTERN_IOC_PQ_CMD_Sync_PQ_table_bin_ENABLE = 122,
	VPQ_EXTERN_IOC_PQ_CMD_GET_Data_Access = 123,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_LEVEL = 124,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL_001 = 125,
	VPQ_EXTERN_IOC_PQ_CMD_SET_Panel_Dither = 126,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_SOURCE_TYPE = 127,

	VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_byAP = 128,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_byAP = 129,
	VPQ_EXTERN_IOC_PQ_CMD_SET_Sharpness_byAP = 130,
	VPQ_EXTERN_IOC_PQ_CMD_SET_CSC_byAP = 131,
	VPQ_EXTERN_IOC_PQ_CMD_SET_NR_byAP = 132,
	VPQ_EXTERN_IOC_PQ_CMD_SET_WBBL_byAP = 133,
	VPQ_EXTERN_IOC_PQ_CMD_SET_WB_BS_byAP = 134,
	VPQ_EXTERN_IOC_PQ_CMD_SET_Black_Adjust_byAP = 135,

	// max is 255, add new id to "vpq_extend_ioc_pq_cmd_2"
};

enum vpq_extend_ioc_pq_cmd_2
{
	VPQ_EXTERN_IOC_PQ_CMD_Sync_TCON_table_bin_ENABLE = 10,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_HDR_TABLE = 11,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_dat = 12,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_size = 13,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DDOMAIN3DLUT_GAMMA = 14,
	VPQ_EXTERN_IOC_PQ_CMD_INIT_DDOMAIN3DLUT_GAMMA_TABLE = 15,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HUE_HISTOGRAM = 16,
	VPQ_EXTERN_IOC_PQ_CMD_GET_SAT_HISTOGRAM = 17,

	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU = 18,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_size = 19,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_item = 20,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_ID = 21,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_ID = 22,
	//VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_ID = 23,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_item = 24,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_ID = 25,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_ID = 26,
	//VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_TWOLAYER_ID = 27,

	VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBYHDR_ENABLE 	= 28,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYHDR_ENABLE 	= 29,
	VPQ_EXTERN_IOC_PQ_CMD_SETGAMMA_TABLESIZE		= 30,
	//VPQ_EXTERN_IOC_PQ_CMD_GET_HISTODATA_APL		= 31,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_MODE_TYPE 		= 31,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL 		= 32,
	VPQ_EXTERN_IOC_PQ_CMD_HIGHLIGHTWINDOW_FORDEMO = 33,
	VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_EOTF		= 34,
	VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_OETF		= 35,
	VPQ_EXTERN_IOC_PQ_CMD_COLORSPACE_HSI			=36,

	//VPQ_EXTERN_IOC_PQ_CMD_SET_PANORAMA_TYPE 		= 38,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DYNAMIC_RANGE         = 37,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DYNAMIC_RANGE_CUR_SRC = 38,
	VPQ_EXTERN_IOC_PQ_CMD_SET_INTERNAL_PARTTEN_1W   = 39,
	//VPQ_EXTERN_IOC_PQ_CMD_SET_VDPQ_MEM_ENABLE = 42,

	VPQ_EXTERN_IOC_CMD_Sync_PQ_table_bin_ENABLE = 40,
};

enum vpq_extend_ioc_pq_eng_menu_cmd
{
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU = 0,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_size = 1,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_item = 2,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_ID = 3,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_ID = 4,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_ID = 5,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_item = 12,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_ID = 13,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_ID = 14,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_TWOLAYER_ID = 15,
};


enum vpq_extend_ioc_pq_cmd_tv002
{
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_EXT_FUN_EN = 10,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_BLE = 11,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_BLE = 12,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SGAMMA = 13,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SGAMMA = 14,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MAGIC_GAMMA = 15,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MAGIC_GAMMA = 16,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SR = 17,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SR = 18,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_LIVE_COLOUR = 19,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_LIVE_COLOUR = 20,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MASTERED_4K = 21,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MASTERED_4K = 22,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_PROJECT_STYLE = 23,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_POWER_SAVING_MODE = 24,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_UI_BACKLIGHT = 25,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_DBC_BACKLIGHT = 26,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_UI_PICTURE_MODE = 27,

	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Intelligent_Pic_Enable = 28,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Intelligent_Pic_Optimisation = 29,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_Intelligent_Pic_Signal_Lv_Indicator_ONOFF = 30,
	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_Intelligent_Pic_Signal_Level = 31,

	VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_HDR_TYPE = 32,

};


enum vpq_extend_ioc_pq_TV030_cmd
{
	VPQ_EXTERN_IOC_PQ_CMD_SET_ODTBL_TV030 						=0,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VALCTBL_TV030 					=1,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DEMURATBL_TV030				=2,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OUTPUTGAMMATBL_TV030			=3,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL_TV030				=4,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_CURVE_TV030				=5,

	VPQ_EXTERN_IOC_PQ_CMD_GET_MEMCLD_ENABLE_TV030 	=10,
	VPQ_EXTERN_IOC_PQ_CMD_SET_MEMCLD_ENABLE_TV030	=11,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_PicInfo_TV030		=12,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLK_HVNUM_TV030		=13,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SPLIT_DEMO_TV030		=14,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LD_Enable_TV030			=15,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLORMATRIXSRGB_TV030	=16,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLKAPL_TV030			=17,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LCBLKSIZE_TV030			=18,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LOWDELAY_MODE_TV030	=19,
	VPQ_EXTERN_IOC_PQ_CMD_GET_LC_HISTOGRAM_TV030		=20,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LCHISBIN_TV030			=21,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_APL_TV030		=22,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MAX_TV030		=23,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MIN_TV030		=24,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PARTTENFORAUTOGAMMA_TV030	=25,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PICTUREMODE_TV030				=26,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS_OSDLAYER_TV030		=27,
	VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST_OSDLAYER_TV030		=28,
	VPQ_EXTERN_IOC_PQ_CMD_GET_PIXELINFO_TV030					=29,
	VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_TABLE_TV030				=30,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DYNAMIC_RANGE_TV030			=31,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DYNAMIC_RANGE_CUR_SRC_TV030	=32,
	VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_MODE_TYPE_TV030			=33,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLORSPACE_HSI					=34,
	VPQ_EXTERN_IOC_PQ_CMD_SET_MAGICGAMMA_TV030				=35,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PANORAMA_TYPE_TV030 	 		= 36,
	VPQ_EXTERN_IOC_PQ_CMD_HIGHLIGHTWINDOW_FORDEMO_TV030 	= 37,
	VPQ_EXTERN_IOC_PQ_CMD_SET_OSDPIC_FLAG_TV030 				= 38,
	VPQ_EXTERN_IOC_PQ_CMD_SETGAMMA_TABLESIZE_TV030			= 39,
	VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_EOTF_TV030 			= 40,
	VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_OETF_TV030 			= 41,
	VPQ_EXTERN_IOC_PQ_CMD_SET_INTERNAL_PARTTEN_1W_TV030   	= 42,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SET_RGBWTOSRGBMATRIX_TV030 	= 43,
	VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_HIS_MAXRGB 				=44,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ICMTABLE 						=45,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ISR 							=46,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_7_AXIS_TV030 				= 47,
	VPQ_EXTERN_IOC_PQ_CMD_GET_ICM_7_AXIS_TV030 				= 48,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_PICTURE_MODE_WEIGHTING_TV030 = 49,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DCC_PICTURE_MODE_WEIGHTING_TV030 = 50,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DECONTOUR_ENABLE_TV030 		= 51,
	VPQ_EXTERN_IOC_PQ_CMD_GET_DECONTOUR_ENABLE_TV030 		= 52,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DECONTOURLEVEL 				=53,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYBACKLIGHT_TV030 		=54,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SET_GAMMA_CURVE				=55,
	VPQ_EXTERN_IOC_SET_SET_DEMURA_CURVE                    =56,
	VPQ_EXTERN_IOC_PQ_CMD_SET_PanelMaxLuminance_TV030	   =57,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LOCALCONTRAST_LEVEL_TV030 		=107,
	VPQ_EXTERN_IOC_PQ_CMD_SET_3DLUT_DATA_TV030		= 109,
	VPQ_EXTERN_IOC_PQ_CMD_GET_AIPQ_SUPPORTMODE =110,
};

enum vpq_extend_ioc_pq_cmd_tv043
{

	VPQ_EXTERN_IOC_PQ_CMD_SET_DCL_W = 0,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DCL_B = 1,
	VPQ_EXTERN_IOC_PQ_CMD_SET_VIDEO_CURVE = 2,
	VPQ_EXTERN_IOC_PQ_CMD_SET_BLUE_STRETCH = 3,
	VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_BY_EXPONENT_OFFSET = 4,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLORTEMP_AFTER_GAMMA = 5,
	VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_TABLEIDX = 6,
	VPQ_EXTERN_IOC_PQ_CMD_SET_COLORSPACE = 7,
	VPQ_EXTERN_IOC_PQ_CMD_SET_LOCAL_CONTRAST = 8,
	VPQ_EXTERN_IOC_PQ_CMD_SET_TONEMAPPING_TABLEIDX = 9,
	VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYBACKLIGHT = 10,
	VPQ_EXTERN_IOC_PQ_CMD_SET_SET_RGBWTOSRGBMATRIX = 11,
};



#define VPQ_EXTERN_IOC_INIT						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_INIT)
#define VPQ_EXTERN_IOC_UNINIT						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_UNINIT)
#define VPQ_EXTERN_IOC_OPEN						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_OPEN)
#define VPQ_EXTERN_IOC_CLOSE						_IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_CLOSE)
#define VPQ_EXTERN_IOC_INIT_PRJ_ID				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_INIT_PRJ_ID, unsigned int)

#define VPQ_EXTERN_IOC_REGISTER_NEW_VIPTABLE _IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_REGISTER_NEW_VIPTABLE)
#define VPQ_EXTERN_IOC_SET_VGA_ADCGainOffset  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VGA_ADCGainOffset, unsigned int)
#define VPQ_EXTERN_IOC_SET_YPBPR_ADCGainOffset  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_YPBPR_ADCGainOffset, unsigned int)
#define VPQ_EXTERN_IOC_SET_SLR_VIP_TABLE_CUSTOM_TV001  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE_CUSTOM_TV001, unsigned int)
#define VPQ_EXTERN_IOC_SET_SLR_VIP_TABLE  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_VIP_TABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_TCON_ENABLE_CTRL  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_TCON_ENABLE_CTRL, unsigned int)
#define VPQ_EXTERN_IOC_SET_OD_SETTING_TABLE  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_OD_SETTING_TABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_OD_TABLE  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_OD_TABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_OD_TABLE_TEST  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_OD_TABLE_TEST, unsigned int)
#define VPQ_EXTERN_IOC_SET_DeMura  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DeMura, unsigned int)
#define VPQ_EXTERN_IOC_SET_VALC  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VALC, unsigned int)
#define VPQ_EXTERN_IOC_SET_VALCprotectSetting  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VALCprotectSetting, unsigned int)
#define VPQ_EXTERN_IOC_SET_LEDOutGamma  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_LEDOutGamma, unsigned int)
#define VPQ_EXTERN_IOC_SET_Output_InvOutput_Gamma  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_Output_InvOutput_Gamma, unsigned int)


#define VPQ_EXTERN_IOC_SET_PIC_MODE_DATA  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA, unsigned int)
#define VPQ_EXTERN_IOC_SET_PIC_MODE_DATA_defaultPictureModeSet  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_defaultPictureModeSet, unsigned int)
#define VPQ_EXTERN_IOC_SET_PIC_MODE_DATA_DolbyHDRPictureModeSet  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PIC_MODE_DATA_DolbyHDRPictureModeSet, unsigned int)

#define VPQ_EXTERN_IOC_SET_StructColorDataType  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataType_defaultSDColorData  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultSDColorData, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataType_defaultHDColorData  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataType_defaultHDColorData, unsigned int)

#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_DATA  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_DATA_defColorTempSet  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_DATA_defColorTempSet, unsigned int)

#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_defaultColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_defaultColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_AvColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_AvColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_YppColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_YppColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_VgaColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_VgaColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_HdmiColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiColorFacMode, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacModeType_HdmiSDColorFacMode  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacModeType_HdmiSDColorFacMode, unsigned int)

#define VPQ_EXTERN_IOC_GET_CUR_SRC_FMT  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_CUR_SRC_FMT, unsigned int)
#define VPQ_EXTERN_IOC_GET_VIP_SRC_TIMING  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_TIMING, unsigned int)
#define VPQ_EXTERN_IOC_SET_StructColorDataFacMode_EXTERN  _IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_StructColorDataFacMode_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_GET_VIP_SRC_RESYNC  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_VIP_SRC_RESYNC, unsigned int)
#define VPQ_EXTERN_IOC_SET_VIP_SRC_RESYNC  _IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_SRC_RESYNC, unsigned int)
#define VPQ_EXTERN_IOC_SET_VIP_SET_VIP_HANDLER_RESET  _IO(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VIP_HANDLER_RESET)

#define VPQ_EXTERN_IOC_GET_BRIGHTNESS				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_BRIGHTNESS, unsigned int)
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS, unsigned int)
#define VPQ_EXTERN_IOC_GET_CONTRAST				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_CONTRAST, unsigned int)
#define VPQ_EXTERN_IOC_SET_CONTRAST				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST, unsigned int)
#define VPQ_EXTERN_IOC_GET_SATURATION				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SATURATION, unsigned int)
#define VPQ_EXTERN_IOC_SET_SATURATION				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SATURATION, unsigned int)
#define VPQ_EXTERN_IOC_GET_HUE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HUE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HUE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HUE, unsigned int)
#define VPQ_EXTERN_IOC_GET_NR				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_NR, unsigned int)
#define VPQ_EXTERN_IOC_SET_NR				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_NR, unsigned int)
#define VPQ_EXTERN_IOC_GET_SHARPNESS				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SHARPNESS, unsigned int)
#define VPQ_EXTERN_IOC_SET_SHARPNESS_EXTERN				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SHARPNESS_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_GET_DE_BLOCKING				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DE_BLOCKING, unsigned int)
#define VPQ_EXTERN_IOC_SET_DE_BLOCKING				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DE_BLOCKING, unsigned int)
#define VPQ_EXTERN_IOC_GET_DE_RINGING				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DE_RINGING, unsigned int)
#define VPQ_EXTERN_IOC_SET_DE_RINGING				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DE_RINGING, unsigned int)
#define VPQ_EXTERN_IOC_GET_COLOR_TEMP				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_TEMP, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_EXTERN				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_TEMP_LEVEL					_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_TEMP_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_GET_COLOR_GAIN				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_COLOR_GAIN, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLOR_GAIN_EXTERN				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_COLOR_GAIN_EXTERN, unsigned int)
#define VPQ_EXTERN_IOC_GET_FLESH_TONE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_FLESH_TONE, unsigned int)
#define VPQ_EXTERN_IOC_SET_FLESH_TONE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_FLESH_TONE, unsigned int)
#define VPQ_EXTERN_IOC_GET_BACKLIGHT				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_BACKLIGHT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_PANEL_BL				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PANEL_BL, unsigned int)
#define VPQ_EXTERN_IOC_GET_GAMMA_NUM			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_GAMMA_NUM, unsigned int)
#define VPQ_EXTERN_IOC_SET_GAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_MODULE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_MODULE, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_MODULE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_MODULE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DEMO				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DEMO, unsigned int)
#define VPQ_EXTERN_IOC_GET_DEBUG_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DEBUG_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DEBUG_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DEBUG_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HISTOGRAM				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HISTOGRAM, unsigned int)
#define VPQ_EXTERN_IOC_GET_SR_LEVEL				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SR_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_SET_SR_LEVEL				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SR_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_SET_BLACK_PATTERN_OUTPUT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_BLACK_PATTERN_OUTPUT, unsigned int)
#define VPQ_EXTERN_IOC_SET_WHITE_PATTERN_OUTPUT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_WHITE_PATTERN_OUTPUT, unsigned int)
#define VPQ_EXTERN_IOC_GET_OD_LEVEL				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_OD_LEVEL, unsigned int)
#define VPQ_EXTERN_IOC_SET_OD_READ_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_OD_READ_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_SRC_HDR_INFO				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SRC_HDR_INFO, unsigned int)
#define VPQ_EXTERN_IOC_GET_SDR2HDR				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_SDR2HDR, unsigned int)
#define VPQ_EXTERN_IOC_SET_SDR2HDR				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_SDR2HDR, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR_TYPE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_TYPE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DCI_TYPE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DCI_TYPE, unsigned int)
#define VPQ_EXTERN_IOC_GET_DOLBY_HDR_PIC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBY_HDR_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DOLBY_HDR_PIC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBY_HDR_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR10_ENABLE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR10_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HDR10_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HDR10_ENABLE, unsigned int)
//#define VPQ_EXTERN_IOC_GET_DOLBYHDR_ENABLE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBYHDR_ENABLE, unsigned int)
//#define VPQ_EXTERN_IOC_SET_DOLBYHDR_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYHDR_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DREAM_PANEL_LOG_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_LOG_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_DREAM_PANEL_BACKLIGHT				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DREAM_PANEL_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_DREAM_PANEL_BACKLIGHT				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DREAM_PANEL_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_GET_DCC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DCC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DCC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_ICM_TBL_IDX				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_ICM_TBL_IDX, unsigned int)
#define VPQ_EXTERN_IOC_SET_ICM_TBL_IDX				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_TBL_IDX, unsigned int)
#define VPQ_EXTERN_IOC_GET_FILM_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_FILM_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_FILM_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDMI_CSC_DATA_RANGE_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDMI_CSC_DATA_RANGE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HDMI_CSC_DATA_RANGE_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_CSC_DATA_RANGE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR_FORCE_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_FORCE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_HDR_FORCE_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_HDR_FORCE_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_CINEMA_PIC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_CINEMA_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_CINEMA_PIC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_CINEMA_PIC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_BYPASS_LV				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_PQ_BYPASS_LV, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_BYPASS_LV				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_BYPASS_LV, unsigned int)
#define VPQ_EXTERN_IOC_GET_GDBC_MODE				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_GDBC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_SET_GDBC_MODE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_GDBC_MODE, unsigned int)
#define VPQ_EXTERN_IOC_GET_DCR_BACKLIGHT				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_DCR_BACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_VDPQ_MEMORY_ENABLE			_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_VDPQ_MEM_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_HISTODATA_APL				_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_HISTODATA_APL, unsigned int)
#define VPQ_EXTERN_IOC_SET_PANORAMA_TYPE					_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PANORAMA_TYPE, unsigned int)
#define VPQ_EXTERN_IOC_SET_OUTGAMMA_SCURVE					_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_OUTGAMMA_SCURVE, unsigned int)

#define VPQ_EXTERN_IOC_SET_GAMMA_LEVEL_001				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL_001, unsigned int)
#define VPQ_EXTERN_IOC_SET_Panel_Dither				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_Panel_Dither, unsigned int)
#define VPQ_EXTERN_IOC_Sync_PQ_table_bin_ENABLE			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_Sync_PQ_table_bin_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_Data_Access			_IOR(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_GET_Data_Access, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_SOURCE_TYPE				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_PQ_SOURCE_TYPE, unsigned int)

#define VPQ_EXTERN_IOC_SET_ICM_byAP				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_byAP, HAL_VPQ_DATA_EXTERN_T)
#define VPQ_EXTERN_IOC_SET_DCC_byAP				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_byAP, HAL_VPQ_DATA_EXTERN_T)
#define VPQ_EXTERN_IOC_SET_Sharpness_byAP				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_Sharpness_byAP, HAL_VPQ_DATA_EXTERN_T)
#define VPQ_EXTERN_IOC_SET_CSC_byAP				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_CSC_byAP, HAL_VPQ_DATA_EXTERN_T)
#define VPQ_EXTERN_IOC_SET_NR_byAP				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_NR_byAP, HAL_VPQ_DATA_EXTERN_T)
#define VPQ_EXTERN_IOC_SET_WBBL_byAP				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_WBBL_byAP, HAL_VPQ_DATA_EXTERN_T)
#define VPQ_EXTERN_IOC_SET_WB_BS_byAP				_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_WB_BS_byAP, HAL_VPQ_DATA_EXTERN_T)
#define VPQ_EXTERN_IOC_SET_Black_Adjust_byAP			_IOW(VPQ_EXTERN_IOC_MAGIC, VPQ_EXTERN_IOC_PQ_CMD_SET_Black_Adjust_byAP, HAL_VPQ_DATA_EXTERN_T)

#define VPQ_EXTERN_IOC_GET_HUE_HISTOGRAM				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_HUE_HISTOGRAM, unsigned int)
#define VPQ_EXTERN_IOC_GET_SAT_HISTOGRAM				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_SAT_HISTOGRAM, unsigned int)
#define VPQ_EXTERN_IOC_Sync_TCON_table_bin_ENABLE			_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_Sync_TCON_table_bin_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_SLR_HDR_TABLE  _IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_SLR_HDR_TABLE, unsigned char)
#define VPQ_EXTERN_IOC_GET_LC_Blight_dat			_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_dat, unsigned int)
#define VPQ_EXTERN_IOC_GET_LC_Blight_size			_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_Blight_size, unsigned int)
#define VPQ_EXTERN_IOC_SET_DDOMAIN3DLUT_GAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_DDOMAIN3DLUT_GAMMA, unsigned char)
#define VPQ_EXTERN_IOC_INIT_DDOMAIN3DLUT_GAMMA_TABLE		_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_INIT_DDOMAIN3DLUT_GAMMA_TABLE, unsigned char)
#define VPQ_EXTERN_IOC_GET_DOLBYHDR_ENABLE				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_DOLBYHDR_ENABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DOLBYHDR_ENABLE				_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYHDR_ENABLE, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_size				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_size, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_item				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_item, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_ID				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_ID, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENG_ID				_IOWR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_ID, unsigned int)
//#define VPQ_EXTERN_IOC_SET_PQ_ENG_ID				_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_ID, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_MENU_item			_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_item, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_MENU_ID			_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_ID, unsigned int)
//#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_ID				_IOWR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_ID, unsigned int)
//#define VPQ_EXTERN_IOC_SET_PQ_ENG_TWOLAYER_ID				_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_TWOLAYER_ID, unsigned int)
//#define VPQ_EXTERN_IOC_SET_INTERNAL_PARTTEN_1W			_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_INTERNAL_PARTTEN_1W, unsigned int)
//#define VPQ_EXTERN_IOC_SET_PQ_SETGAMMA_TABLESIZE			_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SETGAMMA_TABLESIZE, unsigned int)
//#define VPQ_EXTERN_IOC_GET_HISTODATA_APL				_IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_HISTODATA_APL, unsigned int)
//#define VPQ_EXTERN_IOC_SET_HDMI_MODE_TYPE               _IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_MODE_TYPE, unsigned char)
//#define VPQ_EXTERN_IOC_SET_GAMMA_LEVEL				_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL, unsigned int)
//#define VPQ_EXTERN_IOC_SET_HIGHLIGHTWINDOW_FORDEMO	_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_HIGHLIGHTWINDOW_FORDEMO, unsigned int)
//#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_EOTF	_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_EOTF, unsigned int)
//#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_OETF	_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_OETF, unsigned int)
//#define VPQ_EXTERN_IOC_SET_COLORSPACE_HSI	_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_COLORSPACE_HSI, unsigned int)
//#define VPQ_EXTERN_IOC_SET_PQ_VDPQ_MEMORY_ENABLE			_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_VDPQ_MEM_ENABLE, unsigned int)
//#define VPQ_EXTERN_IOC_GET_DYNAMIC_RANGE _IOR(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_GET_DYNAMIC_RANGE, unsigned char)
//#define VPQ_EXTERN_IOC_SET_DYNAMIC_RANGE_CUR_SRC _IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_DYNAMIC_RANGE_CUR_SRC, unsigned char)
//#define VPQ_EXTERN_IOC_SET_PANORAMA_TYPE					_IOW(VPQ_EXTERN_IOC_MAGIC_2, VPQ_EXTERN_IOC_PQ_CMD_SET_PANORAMA_TYPE, unsigned int)

#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU				_IOR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_size				_IOR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_size, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_item				_IOR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_item, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENGMENU_ID				_IOR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENGMENU_ID, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_ID				_IOWR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_ID, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_ENG_ID				_IOW(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_ID, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_MENU_item			_IOR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_item, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_MENU_ID			_IOR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_MENU_ID, unsigned int)
#define VPQ_EXTERN_IOC_GET_PQ_ENG_TWOLAYER_ID				_IOWR(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_GET_ENG_TWOLAYER_ID, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_ENG_TWOLAYER_ID				_IOW(VPQ_EXTERN_IOC_MAGIC_ENG_MENU, VPQ_EXTERN_IOC_PQ_CMD_SET_ENG_TWOLAYER_ID, unsigned int)

#define VPQ_EXTERN_IOC_SET_TV002_EXT_FUN_EN			_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_EXT_FUN_EN, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_BLE				_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_BLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_BLE				_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_BLE, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_SGAMMA				_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SGAMMA, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_SGAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SGAMMA, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_MAGIC_GAMMA				_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MAGIC_GAMMA, VIP_MAGIC_GAMMA_Curve_Driver_Data)
#define VPQ_EXTERN_IOC_SET_TV002_MAGIC_GAMMA				_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MAGIC_GAMMA, VIP_MAGIC_GAMMA_Curve_Driver_Data)
#define VPQ_EXTERN_IOC_GET_TV002_SR				_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_SR, RTK_TV002_SR_T)
#define VPQ_EXTERN_IOC_SET_TV002_SR				_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_SR, RTK_TV002_SR_T)
#define VPQ_EXTERN_IOC_GET_TV002_LIVE_COLOUR				_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_LIVE_COLOUR, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_LIVE_COLOUR				_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_LIVE_COLOUR, unsigned int)
#define VPQ_EXTERN_IOC_GET_TV002_MASTERED_4K				_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_MASTERED_4K, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_MASTERED_4K				_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_MASTERED_4K, unsigned int)
#define VPQ_EXTERN_IOC_SET_TV002_PROJECT_STYLE				_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_PROJECT_STYLE, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_DBC_POWER_SAVING_MODE	_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_POWER_SAVING_MODE, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_DBC_UI_BACKLIGHT	_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_DBC_UI_BACKLIGHT, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_DBC_BACKLIGHT	_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_DBC_BACKLIGHT, unsigned char)
#define VPQ_EXTERN_IOC_SET_TV002_UI_PICTURE_MODE	_IOW(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_SET_TV002_UI_PICTURE_MODE, unsigned char)
#define VPQ_EXTERN_IOC_GET_TV002_HDR_TYPE			_IOR(VPQ_EXTERN_IOC_MAGIC_TV002, VPQ_EXTERN_IOC_PQ_CMD_GET_TV002_HDR_TYPE, unsigned int)

/*------------------------------sync TV030------------------------------*/
#define VPQ_EXTERN_IOC_SET_ODTBL_TV030					_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_ODTBL_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_VALCTBL_TV030					_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_VALCTBL_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_DEMURATBL_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_DEMURATBL_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_OUTPUTGAMMATBL_TV030		_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_OUTPUTGAMMATBL_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_GAMMA_LEVEL_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_LEVEL_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_GAMMA_CURVE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_CURVE_TV030, unsigned int)

#define VPQ_EXTERN_IOC_SET_INTERNAL_PARTTEN_1W_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_INTERNAL_PARTTEN_1W_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_PQ_SETGAMMA_TABLESIZE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SETGAMMA_TABLESIZE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_HIGHLIGHTWINDOW_FORDEMO_TV030	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_HIGHLIGHTWINDOW_FORDEMO_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_EOTF_TV030	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_EOTF_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_OETF_TV030	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_BRIGHTNESS_LUT_OETF_TV030, unsigned int)

#define VPQ_EXTERN_IOC_GET_MEMCLD_ENABLE_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_MEMCLD_ENABLE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_MEMCLD_ENABLE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_MEMCLD_ENABLE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_HDR_PicInfo_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_PicInfo_TV030, unsigned char)
#define VPQ_EXTERN_IOC_GET_HDR_HIS_MAXRGB				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HDR_HIS_MAXRGB, unsigned char)
#define VPQ_EXTERN_IOC_SET_LOCALCONTRAST_LEVEL_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_LOCALCONTRAST_LEVEL_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_GAMMA_CURVE			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_SET_GAMMA_CURVE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DEMURA_CURVE			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_SET_SET_DEMURA_CURVE, _HAL_VPQ_DATA_T_TV030)


#define VPQ_EXTERN_IOC_GET_LC_BLK_HVNUM_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLK_HVNUM_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_SPLIT_DEMO_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_SPLIT_DEMO_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_LD_Enable_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LD_Enable_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_COLORMATRIXSRGB_TV030		_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_COLORMATRIXSRGB_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_LC_BLKAPL_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_BLKAPL_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_LCBLKSIZE_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_LCBLKSIZE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_LOWDELAY_MODE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_LOWDELAY_MODE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_LC_HISTOGRAM_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_LC_HISTOGRAM_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_LC_HISBIN_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_LCHISBIN_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_HistoData_APL_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_APL_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_HistoData_Min_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MIN_TV030, signed int)
#define VPQ_EXTERN_IOC_GET_HistoData_Max_TV030			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_HistoData_MAX_TV030, signed int)
#define VPQ_EXTERN_IOC_SET_PARTTENFORAUTOGAMMA_TV030	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_PARTTENFORAUTOGAMMA_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_PICTUREMODE_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_PICTUREMODE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_OSDLAYER_TV030	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_BRIGHTNESS_OSDLAYER_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_CONTRAST_OSDLAYER_TV030		_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_CONTRAST_OSDLAYER_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_PIXELINFO_TV030  				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_PIXELINFO_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_FILM_TABLE_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_FILM_TABLE_TV030	, unsigned int)
#define VPQ_EXTERN_IOC_GET_DYNAMIC_RANGE_TV030 			_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_DYNAMIC_RANGE_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_DYNAMIC_RANGE_CUR_SRC_TV030 	_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_DYNAMIC_RANGE_CUR_SRC_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_HDMI_MODE_TYPE_TV030             		_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_HDMI_MODE_TYPE_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_COLORSPACE_HSI					_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_COLORSPACE_HSI, unsigned int)
#define VPQ_EXTERN_IOC_SET_MAGICGAMMA_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_MAGICGAMMA_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_OSDPIC_FLAG_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_OSDPIC_FLAG_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_RGBWTOSRGBMATRIX_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_SET_RGBWTOSRGBMATRIX_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_PanelMaxLuminance_TV030			_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_PanelMaxLuminance_TV030, unsigned char)
#define VPQ_EXTERN_IOC_SET_ICMTABLE 							_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_ICMTABLE, unsigned int)
#define VPQ_EXTERN_IOC_SET_ISR 							_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_ISR, unsigned int)
#define VPQ_EXTERN_IOC_SET_ICM_7_Axis_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_7_AXIS_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_ICM_7_Axis_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_ICM_7_AXIS_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_DCC_PICTURE_MODE_WEIGHTING_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_DCC_PICTURE_MODE_WEIGHTING_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_DCC_PICTURE_MODE_WEIGHTING_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_DCC_PICTURE_MODE_WEIGHTING_TV030, unsigned int)
#define VPQ_EXTERN_IOC_GET_DECONTOUR_ENABLE_TV030				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_DECONTOUR_ENABLE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_DECONTOUR_ENABLE_TV030				_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_DECONTOUR_ENABLE_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_DECONTOURLEVEL					_IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_DECONTOURLEVEL, unsigned int)
#define VPQ_EXTERN_IOC_SET_DOLBYBACKLIGHT_TV030                       _IOW(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYBACKLIGHT_TV030, unsigned int)
#define VPQ_EXTERN_IOC_SET_3DLUT_DATA				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_SET_3DLUT_DATA_TV030, unsigned int)


#define VPQ_EXTERN_IOC_SET_INTERNAL_PARTTEN_1W VPQ_EXTERN_IOC_SET_INTERNAL_PARTTEN_1W_TV030
#define VPQ_EXTERN_IOC_SET_PQ_SETGAMMA_TABLESIZE VPQ_EXTERN_IOC_SET_PQ_SETGAMMA_TABLESIZE_TV030
#define VPQ_EXTERN_IOC_SET_HDMI_MODE_TYPE VPQ_EXTERN_IOC_SET_HDMI_MODE_TYPE_TV030
#define VPQ_EXTERN_IOC_SET_GAMMA_LEVEL VPQ_EXTERN_IOC_SET_GAMMA_LEVEL_TV030
#define VPQ_EXTERN_IOC_SET_HIGHLIGHTWINDOW_FORDEMO VPQ_EXTERN_IOC_SET_HIGHLIGHTWINDOW_FORDEMO_TV030
#define VPQ_EXTERN_IOC_GET_DYNAMIC_RANGE VPQ_EXTERN_IOC_GET_DYNAMIC_RANGE_TV030
#define VPQ_EXTERN_IOC_SET_DYNAMIC_RANGE_CUR_SRC VPQ_EXTERN_IOC_SET_DYNAMIC_RANGE_CUR_SRC_TV030
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_EOTF VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_EOTF_TV030
#define VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_OETF VPQ_EXTERN_IOC_SET_BRIGHTNESS_LUT_OETF_TV030
#define VPQ_EXTERN_IOC_GET_AIPQ_SUPPORTMODE				_IOR(VPQ_EXTERN_IOC_MAGIC_TV030, VPQ_EXTERN_IOC_PQ_CMD_GET_AIPQ_SUPPORTMODE, unsigned int)


/*------------------------------sync TV030 end------------------------------*/

/*Add from TV043*/
#define VPQ_EXTERN_IOC_SET_DCL_W			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_DCL_W, unsigned int)
#define VPQ_EXTERN_IOC_SET_DCL_B			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_DCL_B, unsigned int)
#define VPQ_EXTERN_IOC_SET_VIDEO_CURVE			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_VIDEO_CURVE, unsigned int)
#define VPQ_EXTERN_IOC_SET_BLUE_STRETCH			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_BLUE_STRETCH, unsigned int)
#define VPQ_EXTERN_IOC_SET_GAMMA_BY_EXPONENT_OFFSET			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_GAMMA_BY_EXPONENT_OFFSET, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLORTEMP_AFTER_GAMMA			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_COLORTEMP_AFTER_GAMMA, unsigned int)
#define VPQ_EXTERN_IOC_SET_ICM_TABLEIDX			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_ICM_TABLEIDX, unsigned int)
#define VPQ_EXTERN_IOC_SET_COLORSPACE			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_COLORSPACE, unsigned int)
#define VPQ_EXTERN_IOC_SET_DOLBYBACKLIGHT			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_DOLBYBACKLIGHT, unsigned int)
#define VPQ_EXTERN_IOC_SET_LOCAL_CONTRAST			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_LOCAL_CONTRAST, unsigned int)
#define VPQ_EXTERN_IOC_SET_TONEMAPPING_TABLEIDX			_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_TONEMAPPING_TABLEIDX, unsigned int)
#define VPQ_EXTERN_IOC_SET_RGBWTOSRGBMATRIX				_IOW(VPQ_EXTERN_IOC_MAGIC_TV043, VPQ_EXTERN_IOC_PQ_CMD_SET_SET_RGBWTOSRGBMATRIX, unsigned char)

#endif	/* _VPQ_EXTERN_CMD_ID_H_ */
