#
# Makefile for the linux kernel.
#

#KBUILD_CFLAGS += -Wall -Werror

obj-$(CONFIG_RTK_KDRV_JP4K)  += tlv_lib.o
obj-$(CONFIG_RTK_KDRV_JP4K)  += tlv_ring.o
obj-$(CONFIG_RTK_KDRV_JP4K)  += japan4k_dmx.o

